"""!
 @authors Anojan Cherry (anojancherryaji@gmail.com)
 @date 2023-09-14
 @file I3DRobotics_gui_draft_10_mainDisp.py
 @brief Simple gui camera to monitor
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I3DRobotics_gui_draft_10_mainDisp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(QtWidgets.QMainWindow):
    def setupUi(self):
        self.setObjectName("mainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statusIndicator = QtWidgets.QWidget(self.centralwidget)
        self.statusIndicator.setMaximumSize(QtCore.QSize(16777215, 20))
        self.statusIndicator.setObjectName("statusIndicator")
        self.verticalLayout_2.addWidget(self.statusIndicator)
        self.mainDisplay = QtWidgets.QWidget(self.centralwidget)
        self.mainDisplay.setObjectName("mainDisplay")
        self.verticalLayout_2.addWidget(self.mainDisplay)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuRaw_data = QtWidgets.QMenu(self.menubar)
        self.menuRaw_data.setObjectName("menuRaw_data")
        self.menupoint_cloud = QtWidgets.QMenu(self.menubar)
        self.menupoint_cloud.setObjectName("menupoint_cloud")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menustereo_data = QtWidgets.QMenu(self.menubar)
        self.menustereo_data.setObjectName("menustereo_data")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionRefresh = QtWidgets.QAction(self)
        self.actionRefresh.setObjectName("actionRefresh")
        self.menuDevice.addAction(self.actionRefresh)
        self.menuDevice.addSeparator()

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("mainWindow", "I3DRobotics"))
        self.menuDevice.setTitle(_translate("mainWindow", "Device"))
        self.menuRaw_data.setTitle(_translate("mainWindow", "Raw data"))
        self.menupoint_cloud.setTitle(_translate("mainWindow", "point cloud"))
        self.menuPreferences.setTitle(_translate("mainWindow", "Preferences"))
        self.menustereo_data.setTitle(_translate("mainWindow", "stereo data"))
        self.actionRefresh.setText(_translate("mainWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
