# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I3DRobotics_gui_draft_10_toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def setupUi(self):
        self.setObjectName("Form")
        self.resize(331, 354)
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(8, 2, 253, 239))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_devices_refresh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_devices_refresh.setObjectName("btn_devices_refresh")
        self.gridLayout.addWidget(self.btn_devices_refresh, 2, 2, 1, 1)
        self.lbl_device_type = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_device_type.setObjectName("lbl_device_type")
        self.gridLayout.addWidget(self.lbl_device_type, 2, 1, 1, 1)
        self.ckbx_Rectify = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ckbx_Rectify.setObjectName("ckbx_Rectify")
        self.gridLayout.addWidget(self.ckbx_Rectify, 6, 0, 1, 1)
        self.lbl_device_type_ignore = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_device_type_ignore.setObjectName("lbl_device_type_ignore")
        self.gridLayout.addWidget(self.lbl_device_type_ignore, 2, 0, 1, 1)
        self.lbl_device_name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_device_name.setObjectName("lbl_device_name")
        self.gridLayout.addWidget(self.lbl_device_name, 3, 1, 1, 2)
        self.lbl_device_name_ignore = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_device_name_ignore.setObjectName("lbl_device_name_ignore")
        self.gridLayout.addWidget(self.lbl_device_name_ignore, 3, 0, 1, 1)
        self.ckbx_Stereo = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ckbx_Stereo.setObjectName("ckbx_Stereo")
        self.gridLayout.addWidget(self.ckbx_Stereo, 6, 1, 1, 1)
        self.deviceSetting = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deviceSetting.setFont(font)
        self.deviceSetting.setObjectName("deviceSetting")
        self.gridLayout.addWidget(self.deviceSetting, 5, 0, 1, 3)
        self.lbl_exposure = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_exposure.setObjectName("lbl_exposure")
        self.gridLayout.addWidget(self.lbl_exposure, 7, 0, 1, 1)
        self.ckbx_PointCloud = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ckbx_PointCloud.setObjectName("ckbx_PointCloud")
        self.gridLayout.addWidget(self.ckbx_PointCloud, 6, 2, 1, 1)
        self.btn_devices_connect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_devices_connect.setObjectName("btn_devices_connect")
        self.gridLayout.addWidget(self.btn_devices_connect, 1, 2, 1, 1)
        self.spnbx_exposure = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spnbx_exposure.setMinimum(1)
        self.spnbx_exposure.setMaximum(1000000)
        self.spnbx_exposure.setSingleStep(1000)
        self.spnbx_exposure.setProperty("value", 1000)
        self.spnbx_exposure.setObjectName("spnbx_exposure")
        self.gridLayout.addWidget(self.spnbx_exposure, 7, 1, 1, 2)
        self.cbbx_devices = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbbx_devices.setObjectName("cbbx_devices")
        self.gridLayout.addWidget(self.cbbx_devices, 1, 1, 1, 1)
        self.lbl_camera_data = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_camera_data.setFont(font)
        self.lbl_camera_data.setObjectName("lbl_camera_data")
        self.gridLayout.addWidget(self.lbl_camera_data, 0, 0, 1, 3)
        self.lbl_device = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_device.setObjectName("lbl_device")
        self.gridLayout.addWidget(self.lbl_device, 1, 0, 1, 1)
        self.ckbx_capture = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.ckbx_capture.setObjectName("ckbx_capture")
        self.gridLayout.addWidget(self.ckbx_capture, 10, 0, 1, 1)
        self.ckbx_record = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ckbx_record.setObjectName("ckbx_record")
        self.gridLayout.addWidget(self.ckbx_record, 10, 1, 1, 1)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.btn_devices_refresh.setText(_translate("Form", "Refresh"))
        self.lbl_device_type.setText(_translate("Form", "-"))
        self.ckbx_Rectify.setText(_translate("Form", "Rectify"))
        self.lbl_device_type_ignore.setText(_translate("Form", "Type"))
        self.lbl_device_name.setText(_translate("Form", "-"))
        self.lbl_device_name_ignore.setText(_translate("Form", "Name"))
        self.ckbx_Stereo.setText(_translate("Form", "Stereo"))
        self.deviceSetting.setText(_translate("Form", "Device Setting"))
        self.lbl_exposure.setText(_translate("Form", "Exposure"))
        self.ckbx_PointCloud.setText(_translate("Form", "Point cloud"))
        self.btn_devices_connect.setText(_translate("Form", "Connect"))
        self.lbl_camera_data.setText(_translate("Form", "Camera data"))
        self.lbl_device.setText(_translate("Form", "Devices"))
        self.ckbx_capture.setText(_translate("Form", "Capture"))
        self.ckbx_record.setText(_translate("Form", "Record"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
